### ISSUE TITLE
Consider a Licensing Change

### ISSUE THREAD

**Issue by schmittjoh** [chdemko/php-sorted-collections#1]
Would you be open to consider a licensing change to something like MIT, or Apache2? I'm not familar with the current license you are using, but one of the two above seem more widely used for OSS.

**Comment by chdemko** [comment]
The CeCILL-B license is roughly the adaptation of the BSD licence to the [french law](http://www.cecill.info/faq.en.html#bsd) "The principal difference is in the strong obligation of citation which is in CeCILL-B"

**Comment by chdemko** [comment]
I have switched to the bsd3 license.
